### ISSUE TITLE
"atLeastHaVersion" constant preventing auto-fill functionality

### ISSUE THREAD

**Issue by esakowski** [keesschollaart81/vscode-home-assistant#1995]
Any attempt to modify a HA related YAML file with text throws the following error (line 508 of haws.cjs:

```
(node:11300) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at atLeastHaVersion (c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\dist\haws.cjs:508:49)
    at entitiesColl (c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\dist\haws.cjs:1010:32)
    at Object.subscribeEntities (c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\dist\haws.cjs:1013:47)
    at c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\home-assistant\haConnection.js:61:20
    at new Promise (<anonymous>)
    at HaConnection.getHassEntities (c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\home-assistant\haConnection.js:55:33)
    at async HaConnection.getEntityCompletions (c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\home-assistant\haConnection.js:165:26)
    at async HomeAssistantLanguageService.getServiceAndEntityCompletions (c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\haLanguageService.js:174:48)
    at async HomeAssistantLanguageService.onCompletion (c:\Users\sakow\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\haLanguageService.js:121:43)
```

Made the following minor code change - very poor quality, I'm not a programmer - starting at line 507 of haws.cjs .  It seems to be running perfectly now:

```
const atLeastHaVersion = (version, major, minor, patch) => {
    const version2 = "core-2022.3.7";
    const [haMajor, haMinor, haPatch] = version2.split(".", 3);
```

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [X] Smb
- [ ] Other:

**Comment by OpSparkk** [comment]
I was stuck on this problem for couple hours wy my auto fill was not working.
But this fixed the problem!!
thanks

**Comment by sleif** [comment]
Run into the same problem - thanks for the  workaround.

**Comment by parberge** [comment]
I get a similar error:
```
Schemas updated!
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant
/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:508
    const [haMajor, haMinor, haPatch] = version.split(".", 3);
                                                ^

TypeError: Cannot read properties of undefined (reading 'split')
    at atLeastHaVersion (/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:508:49)
    at entitiesColl (/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:1010:32)
    at Object.subscribeEntities (/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:1013:47)
    at /Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/home-assistant/haConnection.js:61:20
    at new Promise (<anonymous>)
    at HaConnection.getHassEntities (/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/home-assistant/haConnection.js:55:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HaConnection.getEntityCompletions (/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/home-assistant/haConnection.js:165:26)
    at async HomeAssistantLanguageService.getServiceAndEntityCompletions (/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/haLanguageService.js:174:48)
    at async HomeAssistantLanguageService.onCompletion (/Users/parberge/.vscode/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/haLanguageService.js:121:43)
 ```
 v 1.27.0 and home assistant core-2022.4.1

**Comment by LunkwillAndFook** [comment]
Found the same bug. Same workaround corrected it.

**Comment by Chr1stian** [comment]
Thanks for the workaround!

**Comment by frenck** [comment]
This issue has been fixed in the latest release of the extension.
