### ISSUE TITLE
V1.27 has connection problems with HomeAssistant in docker at least

### ISSUE THREAD

**Issue by PuckeyP** [keesschollaart81/vscode-home-assistant#2011]
Going back to V1.26 solves it

**Comment by ruaandeysel** [comment]
> Going back to V1.26 solves it

Thanks for spotting this. Fixed my issue by downgrading to 1.26.

**Comment by p1rmas** [comment]
Yes, I also have problems with V1.27 in docker. Downgrading to 1.26 helped. Thank you.

**Comment by Nicholaiii** [comment]
I changed to Core the same day I updated to 1.27. I have no idea which is the culprit, but 1.26 works for me too, so there's definitely a regression of some sort

**Comment by antbarney** [comment]
Just thought I would add the stacktrace I see when trying to connect remotely using 1.27 As everyone else has noted works fine when using v1.26

Discover all configuration files because file://homeassistant/config/lovelace/views/34_3d_printers.yaml got updated and new files were found...
c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\dist\haws.cjs:508
    const [haMajor, haMinor, haPatch] = version.split(".", 3);
                                                ^

TypeError: Cannot read properties of undefined (reading 'split')
    at atLeastHaVersion (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\dist\haws.cjs:508:49)
    at entitiesColl (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\dist\haws.cjs:1010:32)
    at Object.subscribeEntities (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\dist\haws.cjs:1013:47)
    at c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\home-assistant\haConnection.js:61:20
    at new Promise (<anonymous>)
    at HaConnection.getHassEntities (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\home-assistant\haConnection.js:55:33)
    at async HaConnection.getEntityCompletions (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\home-assistant\haConnection.js:165:26)
    at async HomeAssistantLanguageService.getServiceAndEntityCompletions (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\haLanguageService.js:174:48)
    at async HomeAssistantLanguageService.onCompletion (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\out\language-service\src\haLanguageService.js:121:43)
[Info  - 11:05:36 AM] Connection to server got closed. Server will restart.
[Error - 11:05:36 AM] Request textDocument/completion failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\antba\.vscode-insiders\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (node:events:402:35)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
[Error - 11:05:36 AM] Request textDocument/documentSymbol failed.
