### ISSUE TITLE
1.27 crashes determining version

### ISSUE THREAD

**Issue by hanerd** [keesschollaart81/vscode-home-assistant#2024]
1.27 crashes when trying to run against **2022.3.5** both locally and over SSH.  Rolling back to 1.26 resolves the problem.

Please include the related YAML code:
No relevant yaml.  The extension crashes upon startup / retrieving data from HA

Find my Home Assistant Configuration here:
None

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [ ] Linux 

I'm accessing my files:
- [X] From local disk 
- [X] Via remote SSH 
- [ ] Smb
- [ ] Other:  

Relevant error logs.
```
/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:508
    const [haMajor, haMinor, haPatch] = version.split(".", 3);
                                                ^

TypeError: Cannot read properties of undefined (reading 'split')
    at atLeastHaVersion (/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:508:49)
    at entitiesColl (/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:1010:32)
    at Object.subscribeEntities (/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/node_modules/home-assistant-js-websocket/dist/haws.cjs:1013:47)
    at /home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/home-assistant/haConnection.js:61:20
    at new Promise (<anonymous>)
    at HaConnection.getHassEntities (/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/home-assistant/haConnection.js:55:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HaConnection.getEntityCompletions (/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/home-assistant/haConnection.js:165:26)
    at async HomeAssistantLanguageService.getServiceAndEntityCompletions (/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/haLanguageService.js:174:48)
    at async HomeAssistantLanguageService.onCompletion (/home/felix/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.27.0/out/language-service/src/haLanguageService.js:121:43)
    ```

**Comment by antbarney** [comment]
I am not much of a coder, so I have don't know how to fix it. But this looks to be some new logic in the JS websocket package that was updated as one of the changes for 1.26 to 1.27 

"home-assistant-js-websocket": "^7.0.2",
and when you compare the versions from 1.26 to 1.27 
https://github.com/home-assistant/home-assistant-js-websocket/compare/6.0.1...7.0.2

you see that the atLeastHaVersion Const was added to the utils.

And from what I can tell the "version" object that is getting passed to it is undefined
