### ISSUE TITLE
Language server crashing with newest update (1.29.1). 

### ISSUE THREAD

**Issue by tekgeek1205** [keesschollaart81/vscode-home-assistant#2102]
Please include the related YAML code:

Newest update throws errors in Docker. Falling back from 1.29.1 to 1.29.0 fixes things.  Chased my tail for 30 min on that one. Let me know if you need any other logs or anything. 

Here is the docker image I'm using:
https://hub.docker.com/r/codercom/code-server

```YAML
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" target "./dist/*" defined for './dist/' in the package config /home/coder/.local/share/code-server/extensions/keesschollaart.vscode-home-assistant-1.29.1/node_modules/home-assistant-js-websocket/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwInvalidPackageTarget (internal/modules/esm/resolve.js:351:9)
    at resolvePackageTargetString (internal/modules/esm/resolve.js:362:5)
    at resolvePackageTarget (internal/modules/esm/resolve.js:416:12)
    at packageExportsResolve (internal/modules/esm/resolve.js:557:22)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
[Info  - 8:02:18 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" target "./dist/*" defined for './dist/' in the package config /home/coder/.local/share/code-server/extensions/keesschollaart.vscode-home-assistant-1.29.1/node_modules/home-assistant-js-websocket/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwInvalidPackageTarget (internal/modules/esm/resolve.js:351:9)
    at resolvePackageTargetString (internal/modules/esm/resolve.js:362:5)
    at resolvePackageTarget (internal/modules/esm/resolve.js:416:12)
    at packageExportsResolve (internal/modules/esm/resolve.js:557:22)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
[Info  - 8:02:19 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" target "./dist/*" defined for './dist/' in the package config /home/coder/.local/share/code-server/extensions/keesschollaart.vscode-home-assistant-1.29.1/node_modules/home-assistant-js-websocket/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwInvalidPackageTarget (internal/modules/esm/resolve.js:351:9)
    at resolvePackageTargetString (internal/modules/esm/resolve.js:362:5)
    at resolvePackageTarget (internal/modules/esm/resolve.js:416:12)
    at packageExportsResolve (internal/modules/esm/resolve.js:557:22)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
[Info  - 8:02:19 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" target "./dist/*" defined for './dist/' in the package config /home/coder/.local/share/code-server/extensions/keesschollaart.vscode-home-assistant-1.29.1/node_modules/home-assistant-js-websocket/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwInvalidPackageTarget (internal/modules/esm/resolve.js:351:9)
    at resolvePackageTargetString (internal/modules/esm/resolve.js:362:5)
    at resolvePackageTarget (internal/modules/esm/resolve.js:416:12)
    at packageExportsResolve (internal/modules/esm/resolve.js:557:22)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
[Info  - 8:02:19 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" target "./dist/*" defined for './dist/' in the package config /home/coder/.local/share/code-server/extensions/keesschollaart.vscode-home-assistant-1.29.1/node_modules/home-assistant-js-websocket/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwInvalidPackageTarget (internal/modules/esm/resolve.js:351:9)
    at resolvePackageTargetString (internal/modules/esm/resolve.js:362:5)
    at resolvePackageTarget (internal/modules/esm/resolve.js:416:12)
    at packageExportsResolve (internal/modules/esm/resolve.js:557:22)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
[Error - 8:02:19 PM] Connection to server got closed. Server will not be restarted.

```

Find my Home Assistant Configuration here:
[Link to Home Assistant Configuration](<link to repo here>)

Extension runs in:
- [ ] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [x] Other: 

I'm running VS Code on:
- [x] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:

**Comment by frenck** [comment]
Fixed by #2101
