### ISSUE TITLE
Langage Server Fails to Start

### ISSUE THREAD

**Issue by NovaMachina** [keesschollaart81/vscode-home-assistant#3131]
I'm running VS Code via code-server in a k3s cluster. I added this extension and configured it to talk with my HASS installation that is also running on k3s. I get the following output until the server decides to not restart:
```
[Home Assistant Language Server(1750)] Started and initialize received
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant... Tries left: 3
Applying schemas to 8 of your configuration files...
Assigning /config/configuration.yaml the configuration.yaml schema
Assigning /config/automations.yaml the configuration.yaml/automation schema
Assigning /config/blueprints/automation/homeassistant/motion_light.yaml the blueprints/automation schema
Assigning /config/blueprints/automation/homeassistant/notify_leaving_zone.yaml the blueprints/automation schema
Assigning /config/blueprints/script/homeassistant/confirmable_notification.yaml the blueprints/script schema
Assigning /config/automations.yaml the configuration.yaml/automation schema
Assigning /config/scripts.yaml the configuration.yaml/script schema
Assigning /config/scenes.yaml the configuration.yaml/scene schema
Schemas updated!
undefined:1
	
	

SyntaxError: Unexpected token <nul> in JSON at position 1
    at JSON.parse (<anonymous>)
    at WebSocket.handleMessage (/config/.vscode/keesschollaart.vscode-home-assistant-1.40.0-universal/out/language-service/src/home-assistant/socket.js:79:34)
    at callListener (/config/.vscode/keesschollaart.vscode-home-assistant-1.40.0-universal/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/config/.vscode/keesschollaart.vscode-home-assistant-1.40.0-universal/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/config/.vscode/keesschollaart.vscode-home-assistant-1.40.0-universal/node_modules/ws/lib/websocket.js:1203:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.dataMessage (/config/.vscode/keesschollaart.vscode-home-assistant-1.40.0-universal/node_modules/ws/lib/receiver.js:550:14)
    at /config/.vscode/keesschollaart.vscode-home-assistant-1.40.0-universal/node_modules/ws/lib/receiver.js:516:23
    at /config/.vscode/keesschollaart.vscode-home-assistant-1.40.0-universal/node_modules/ws/lib/permessage-deflate.js:309:9

Node.js v18.17.1
```
I'm not sure what the issue is as the error is not very descriptive.

Extension runs in:
- [ ] VS Code for Desktop 
- [ ] Hassio Add-on 
- [x] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [ ] Mac 
- [x] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [x] Other:  code-server via web browser

**Comment by NovaMachina** [comment]
Determined the issue was due to a misconfiguration of the server URL on my end.
